### PR TITLE
Mavenize halfNES

### PR DESCRIPTION
**Pull request by klaushauschild1984**
This pull request solves issue #3.
* all NetBeans specific files are removed
* project could be build by Maven
* dependencies resolved by Maven
* remove compile depenency to Happy Library
* reorganice project layout to maven standard
* redo packaging process

### CODE REVIEW

**Comment by andrew-hoffman** [comment]
Doesn't seem to quite work for me, crashes while generating Javadoc and if I don't generate the Javadoc it crashes immediately in native code. I'm on Windows 7 here, what are you using?

**Comment by andrew-hoffman** [comment]
Here's the runtime error I'm getting http://pastebin.com/5btctFzz

As expected if I remove all references to JInput it builds and runs fine (but without controller support)
Not sure why that's happening yet since the natives are definitely making it into the JAR, they're either not getting extracted properly or not ending up in the classpath.

Javadoc generation crash can be fixed by replacing all <steveonjava@gmail.com> with (steveonjava@gmail.com) and removing the spurious
 
        /**
     * @param args the command line arguments
     */

from ControlsDialog.java and PreferencesDialog.java.

**Comment by klaushauschild1984** [comment]
I see the java doc generation errors and fix them.

**Comment by klaushauschild1984** [comment]
Javadoc generation works now but still with errors. Now for the jinput problem.
FYI: I am at Windows 10.

**Comment by klaushauschild1984** [comment]
Please giv it another try. I go back to JInput-2.0.5.
Now the access violation exception is gone but at my Win 10 machine it still won't run.

**Comment by klaushauschild1984** [comment]
Now it should be compatible to Windows 8, 8.1 and 10.

**Comment by andrew-hoffman** [comment]
Now the binary works on my Windows 10 machine but still fails with an access violation on Win7. It could be JInput's fault except it obviously worked with the old build system. I only have the one Win7 computer to test on though. Need to find a test JNI application that does nothing, build it in a similar way and see if that fails too.

**Comment by klaushauschild1984** [comment]
Minecraft uses JInput and LWJGL in the way I integrated in halfNES.

**Comment by klaushauschild1984** [comment]
Currently I have only Windows 10 for testing. Tomorrow I have access to a Windows 7 machine and look what I could do.

**Comment by andrew-hoffman** [comment]
Seems to run on my cousin's windows 7 computer so maybe it is just me then.

**Comment by klaushauschild1984** [comment]
How much bit? 32 or 64.
To clarify, this compatibility problems already exists before my refactoring. It is not my goal to make thing complecated then before.

**Comment by klaushauschild1984** [comment]
Against which version of JInput are you compiling at you local machine?

**Comment by andrew-hoffman** [comment]
Both windows 7 machines are 64 bit, though I have the 64 bit JDK installed and he doesn't. I get the same problem with JInput 2.0.6 and 2.0.5 (but either way Maven's downloading them so it's not my local files).

**Comment by andrew-hoffman** [comment]
If I uninstall the 64 bit JVM I can now launch it from outside the IDE but not inside (inside is probably using the 64 bit JDK). So that narrows it down.

**Comment by andrew-hoffman** [comment]
After reinstalling JVM 8u66 (x86 version only)

-before rebooting, controller support fails with an UnsatisfiedLinkError but it still loads far enough to get into the UI. Then after loading a game, the emulator freezes after the first frame
-After rebooting once, controller support still fails with UnsatisfiedLinkError but the rest of the emulator works OK

**Comment by andrew-hoffman** [comment]
Out of time to troubleshoot today and need to reinstall IDE now.

**Comment by andrew-hoffman** [comment]
Looks like I can tell Launch4J to use the 32 bit JVM only but that doesn't really fix the problem.

**Comment by klaushauschild1984** [comment]
Your first intension, that the natives are not correctly extracted, was right. Sorry for that.
I looked at the sources of JMonkeyEngine (they do the same way, or I have stolen the idea of extracting the natives from them) and found a tiny difference.
After that the test case passes at a Windows 7 machine. I think and hope this problems are gone.

**Comment by andrew-hoffman** [comment]
right. works for me. Pulling it

**Comment by andrew-hoffman** [comment]
need to fix building instructions in readme and make Launch4J require java 8 but i can do that later

**Pull request merged**
